export const RAW_SCHEDULE_CSV = `ABRIL DE 2026,,
"6 de abril, segunda-feira","Último dia para eleitoras e eleitores domiciliadas(os) no Brasil que não possuem cadastro biométrico na Justiça Eleitoral solicitarem operações de alistamento, transferência e revisão pelo serviço de autoatendimento eleitoral na internet.",1. Verificar com o Márcio se há impacto real dessa medida. 
,,"2. Enviar Ofício-circular às Zonas eleitorais, informando"
,,3. Solicitar divulgação pela ASCOM.
"7 de abril, terça-feira",Início do prazo para o cadastramento de solicitações de DE-PARA do tipo 7 no Sistema ELO e para o envio da respectiva solicitação à CGE.,
MAIO DE 2026,,
"6 de maio, quarta-feira","Último dia para operações de alistamento, transferência e revisão (Lei nº 9.504/1997, art. 91).",
"6 de maio, quarta-feira","Último dia para que eleitoras e eleitores domiciliados no Brasil, que possuam cadastro biométrico válido na Justiça Eleitoral, ou domiciliados no exterior solicitem operações de alistamento, transferência e revisão pelo serviço de autoatendimento eleitoral na internet.",
"7 de maio, quinta-feira","Suspensão das operações de alistamento, transferência e revisão eleitoral, inclusive para requerimentos solicitados por meio do serviço de autoatendimento eleitoral na internet (Lei nº 9.504/1997, art. 91).",
"7 de maio, quinta-feira",Liberação das certidões circunstanciadas no Sistema ELO.,
"7 de maio, quinta-feira","Data a partir da qual, identificadas novas coincidências, as decisões respectivas deverão ser digitadas até o dia 25 de junho de 2026.",
"27 de maio, quarta-feira","Comunicação às Corregedorias Regionais Eleitorais sobre os lotes de RAE não enviados, inclusive os de RAEs diligenciados, bem como sobre os arquivos de biometria pendentes.",
JUNHO DE 2026,,
"3 de junho, quarta-feira","Último dia para envio dos lotes de RAE, incluídos os diligenciados, e dos arquivos de biometria.",
"3 de junho, quarta-feira","Último dia para recebimento, na Corregedoria-Geral Eleitoral, de pedidos de alteração excepcional de situação de RAE.",
"5 de junho, sexta-feira","Data-limite para a Justiça Eleitoral tornar disponível aos partidos políticos a relação de todas(os) as(os) devedoras (es) de multa eleitoral, a qual embasará a expedição das certidões de quitação (Lei nº 9.504/1997, art. 11, § 9º).",
"8 de junho, segunda-feira","Último dia para alteração, indeferimento ou exclusão de RAE pela zona eleitoral.",
"9 de junho, terça-feira",Último dia para a alteração excepcional de situação de RAE solicitada à Corregedoria-Geral Eleitoral.,
"9 de junho, terça-feira","Processamento automático dos formulários de RAE não enviados até essa data pelas zonas eleitorais ao Tribunal Superior Eleitoral, ou com pendências de processamento, à exceção dos lotes criados pelas zonas do exterior e dos requerimentos oriundos de solicitações formuladas por meio do Título Net nas quais não tenha havido, durante o atendimento, coleta obrigatória de dado biométrico ou autenticação biométrica.",
"9 de junho, terça-feira","Último dia para envio, ao TSE, dos lotes de RAE de eleitoras e eleitores cadastradas(os) no exterior.",
"9 de junho, terça-feira",Último dia para disponibilização das biometrias recebidas de órgãos externos para serem validadas nas Eleições 2026.,
"13 de junho, sábado; e","Manutenção preventiva da infraestrutura do cadastro, com indisponibilidade do Sistema ELO e de outros sistemas associados ao cadastro eleitoral, em ambientes de produção e treinamento.",
"14 de junho, domingo","Continuidade da manutenção preventiva da infraestrutura do cadastro e indisponibilidade de sistemas.",
"15 de junho, segunda-feira","Último dia para recebimento, na Corregedoria-Geral Eleitoral, de pedidos de regularização de histórico de inscrições ou de reversão de operações.",
"15 de junho, segunda-feira",Último dia para o TSE processar os lotes de RAE com inscrições de eleitoras e eleitores domiciliadas(os) no exterior.,
"18 de junho, quinta-feira","Último dia para envio, ao TSE, dos lotes de RAE corrigidos no banco de erros.",
"19 de junho, sexta-feira",Último dia para o TSE atualizar o cadastro com as correções do banco de erros.,
"22 de junho, segunda-feira",Último dia para o cadastramento de situações de DE-PARA dos tipos 1 a 5 pela zona eleitoral.,
"23 de junho, terça-feira",Último dia para o cadastramento e a autorização de situação de DE-PARA dos tipos 1 a 5 pelo TRE.,
"24 de junho, quarta-feira",Último dia para o TSE processar as situações de DE-PARA dos tipos 1 a 5.,
"25 de junho, quinta-feira","Último dia para as corregedorias e as zonas eleitorais digitarem as decisões de coincidências.",
"25 de junho, quinta-feira","Último dia para cadastramento de solicitações DE-PARA do tipo 6 pela zona eleitoral.",
"26 de junho, sexta-feira","Último dia para o TSE atualizar o cadastro com as decisões de coincidências.",
"26 de junho, sexta-feira","Último dia para o cadastramento e a autorização de solicitações DE-PARA do tipo 6 pelo TRE.",
"29 de junho, segunda-feira",Último dia para o TSE processar as solicitações de DE-PARA do tipo 6.,
"30 de junho, terça-feira",Último dia para as corregedorias promoverem alterações diretamente no histórico das inscrições e para a Corregedoria-Geral Eleitoral realizar alterações no cadastro.,
"30 de junho, terça-feira","Data a partir da qual os códigos de ASE 019, 043, 337, 361, 370, 450 e 469 digitados pelas zonas eleitorais não alterarão de imediato a situação da inscrição.",
"30 de junho, terça-feira",Último dia para o cadastramento de solicitações DE-PARA do tipo 7 e para o envio da solicitação à CGE.,
JULHO DE 2026,,
"2 de julho, quinta-feira",Último dia para autorização de solicitações de DE-PARA do tipo 7 pela CGE.,
"3 de julho, sexta-feira",Último dia para o TSE processar as solicitações de DE-PARA do tipo 7.,
"3 de julho, sexta-feira",Último dia para atualização automática do CPF de eleitoras e eleitores no Cadastro Eleitoral com base nos dados recebidos da Receita Federal.,
"6 de julho, segunda-feira",Encerramento do processamento do cadastro eleitoral.,
"7 de julho, terça-feira",Início da auditoria das bases de dados do cadastro eleitoral.,
"7 de julho, terça-feira",Data a partir da qual será possível emitir o edital de nomeação das mesas receptoras e do apoio logístico.,
"9 de julho, quinta-feira","Último dia para a conclusão da auditoria das bases de dados do cadastro eleitoral, seguida da carga das seções convencionais, para viabilizar agregação de seção.",
"10 de julho, sexta-feira",Data-limite para o início da extração dos arquivos com foto para folha de votação e para o terminal do mesário.,
"13 de julho, segunda-feira",Início do prazo para o cadastramento de agregação de seções.,
"17 de julho, sexta-feira","Data a partir da qual os locais de votação convencionais para o recebimento de voto em trânsito devem estar habilitados, ou novos locais específicos para voto em trânsito devem estar criados no sistema.",
"17 de julho, sexta-feira","Último dia para a criação, no cadastro eleitoral, de locais de votação em estabelecimentos prisionais e em unidades de internação de adolescentes.",
"18 de julho, sábado",Início da geração dos arquivos para folha de votação.,
"19 de julho, domingo","Data a partir da qual será disponibilizada relação, com atualização diária, de locais de votação com vagas para voto em trânsito e para transferência temporária de militares, agentes de segurança pública e guardas municipais, servidoras e servidores da Justiça Eleitoral, juízas e juízes eleitorais, juízas e juízes auxiliares e promotoras e promotores eleitorais em serviço no dia da eleição.",
"20 de julho, segunda-feira",Divulgação do eleitorado apto para as Eleições 2026.,
"20 de julho, segunda-feira","Início do prazo para a transferência temporária de militares, agentes de segurança pública, guardas municipais, agentes penitenciárias(os), servidoras e servidores da Justiça Eleitoral, juízas e juízes eleitorais, juízas e juízes auxiliares e promotoras e promotores eleitorais em serviço no dia eleição; pessoas com deficiência ou mobilidade reduzida; mesárias e mesários convocadas(os) para apoio logístico; indígenas, quilombolas e pessoas de comunidades tradicionais e de assentamentos rurais; e para habilitação para voto em trânsito e em estabelecimentos prisionais e unidades de internação de adolescentes.",
"22 de julho, quarta-feira","Último dia para disponibilização dos arquivos de eleitoras e eleitores (exceto os relativos à transferência temporária) para folha de votação e para urna eletrônica, inclusive do arquivo de zonas e municípios.",
"23 de julho, quinta-feira",Início do prazo para zonas eleitorais e TREs cadastrarem alocação temporária de seções.,
"23 de julho, quinta-feira",Início da produção dos cadernos de folhas de votação.,
AGOSTO DE 2026,,
"5 de agosto, quarta-feira",Último dia para nomeação de membras e membros das mesas receptoras e do pessoal de apoio logístico para primeiro e eventual segundo turnos e para lançamento dos respectivos códigos de ASE (exceto para estabelecimentos prisionais e mesas específicas para voto em trânsito).,
"20 de agosto, quinta-feira","Último dia para requerimento, alteração ou cancelamento da habilitação para voto em trânsito e em estabelecimentos prisionais e unidades de internação de adolescentes, bem como para transferência temporária de militares, agentes de segurança pública, guardas municipais, servidoras e servidores da Justiça Eleitoral, juízas e juízes eleitorais, juízas e juízes auxiliares e promotoras e promotores eleitorais em serviço no dia eleição; pessoas com deficiência ou mobilidade reduzida; indígenas, quilombolas e pessoas de comunidades tradicionais e de assentamentos rurais.",
"20 de agosto, quinta-feira",Data-limite para que os locais de votação convencionais para recebimento de voto em trânsito estejam habilitados ou novos locais específicos para voto em trânsito estejam criados no sistema.,
"24 de agosto, segunda-feira","Último dia para digitação ou cancelamento dos requerimentos de habilitação para transferência temporária, exceto os formulados por mesárias, mesários, pessoas convocadas para apoio logístico e agentes penitenciárias(os).",
"25 de agosto, terça-feira",Distribuição das inscrições transferidas temporariamente pelas seções dos locais indicados.,
"26 de agosto, quarta-feira","Comunicação, aos TREs, das seções ordinárias com menos de 50 (cinquenta) eleitoras e eleitores e dos locais com pessoas presas provisoriamente em número inferior a 20 (vinte), contabilizando as transferências temporárias.",
"27 de agosto, quinta-feira",Último dia para que as zonas eleitorais promovam a agregação de seções.,
"27 de agosto, quinta-feira","Último dia para que as zonas eleitorais promovam o cancelamento de seções específicas para pessoas presas provisoriamente e adolescentes em unidades de internação, com o consequente cancelamento das respectivas transferências temporárias.",
"28 de agosto, sexta-feira",Último dia para nomeação de membras e membros das mesas receptoras das seções para pessoas presas provisoriamente e adolescentes em unidades de internação e das mesas específicas para voto em trânsito e dos auxiliares de auditoria.,
"28 de agosto, sexta-feira","Último dia para requerimento, alteração ou cancelamento (inclusive da respectiva digitação) da habilitação de transferência temporária de agentes penitenciárias(os), mesárias(os) e pessoas convocadas para apoio logístico.",
"31 de agosto, segunda-feira",Último dia para que os TREs promovam a agregação de seções e o cancelamento de seções específicas para presos provisórios e adolescentes internados.,
SETEMBRO DE 2026,,
"1º de setembro, terça-feira","Último dia para a geração dos pacotes de dados das inscrições transferidas temporariamente, das eleitoras e dos eleitores impedidos e das seções, e para a liberação desses pacotes de dados para carga do sistema de totalização, das urnas e dos demais sistemas do processo eleitoral.",
"1º de setembro, terça-feira",Geração automática de ASE 590 para inscrições transferidas temporariamente para o primeiro turno.,
"1º de setembro, terça-feira","Data-limite para a disponibilização de consulta aos locais de votação, contemplando as solicitações de transferência temporária.",
"2 de setembro, quarta-feira","Data a partir da qual estará disponível a relação definitiva de inscrições transferidas temporariamente, para anotação do impedimento nas folhas de votação.",
"2 de setembro, quarta-feira",Início da produção dos cadernos de votação das seções com inscrições transferidas temporariamente.,
"4 de setembro, sexta-feira",Último dia para o envio ao Tribunal Regional Eleitoral do Distrito Federal (TRE/DF) dos cadernos de votação das eleitoras e dos eleitores do exterior.,
"14 de setembro, segunda-feira",Último dia para os TREs receberem os cadernos de votação.,
"29 de setembro, terça-feira",Último dia para os TREs solicitarem ao TSE a reimpressão dos cadernos de votação nos casos de falha na impressão ou de falta de cadernos.,
OUTUBRO DE 2026,,
"4 de outubro, domingo",PRIMEIRO TURNO DAS ELEIÇÕES,
"4 de outubro, domingo","Início do processamento dos arquivos gerados pela urna eletrônica no primeiro turno, relativos ao Cadastro Eleitoral, inclusive os de justificativas e faltas (JUFA), os de justificativas recebidas pelo e-Título e os de presença das mesárias e dos mesários.",
"5 de outubro, segunda-feira","Suspensão do fornecimento de certidão de quitação pela internet, pelo e-Título e pelo Sistema ELO, bem como da emissão de GRU pela internet.",
"5 de outubro, segunda-feira",Geração e disponibilização do pacote com atualização de fuso horário dos municípios.,
"5 de outubro, segunda-feira",Importação automática das Mesas Receptoras de Justificativa do primeiro para o segundo turno.,
"5 de outubro, segunda-feira",Geração do ASE 590 para eleitoras e eleitores transferidos temporariamente para o segundo turno.,
"7 de outubro, quarta-feira","Último dia para o envio, ao TSE, dos arquivos gerados pela urna eletrônica no primeiro turno, relativos ao Cadastro Eleitoral, inclusive os de JUFA e os de presença das mesárias e dos mesários.",
"8 de outubro, quinta-feira",Início do cadastramento de Mesas Receptoras de Justificativa e alocação temporária de seções para o segundo turno.,
"11 de outubro, domingo","Data-limite para a conclusão do processamento dos arquivos gerados pela urna eletrônica no primeiro turno, relativos ao Cadastro Eleitoral, inclusive os de justificativas e faltas (JUFA), os de justificativas recebidas pelo e-Título e os de presença das mesárias e dos mesários.",
"12 de outubro, segunda-feira","Data-limite para o reinício da emissão de certidão de quitação pela internet, pelo e-Título e pelo Sistema ELO e para emissão de GRU pela internet.",
"20 de outubro, terça-feira","Fim do prazo para os TREs solicitarem, para o segundo turno, a reimpressão de cadernos de votação danificados ou extraviados durante a votação no primeiro turno.",
"23 de outubro, sexta-feira","Último dia para a empresa contratada entregar, nos TREs, a reimpressão dos cadernos de votação danificados ou extraviados durante a votação no primeiro turno.",
"25 de outubro, domingo",SEGUNDO TURNO DAS ELEIÇÕES,
"25 de outubro, domingo","Início do processamento dos arquivos gerados pela urna eletrônica no segundo turno, relativos ao Cadastro Eleitoral, inclusive os de justificativas e faltas (JUFA), os de justificativas recebidas pelo e-Título e os de presença das mesárias e dos mesários.",
"26 de outubro, segunda-feira","Reinício da atualização da situação das inscrições pelos códigos de ASE 019, 043, 337, 361, 370, 450 e 469, inclusive os digitados no período de 30 de junho de 2026 a 25 de outubro de 2026.",
"26 de outubro, segunda-feira","Suspensão do fornecimento de certidão de quitação pela internet, pelo e-Título e pelo Sistema ELO, bem como da emissão de GRU pela internet.",
"29 de outubro, quinta-feira","Último dia para o envio dos arquivos gerados pela urna eletrônica no segundo turno, relativos ao Cadastro Eleitoral, inclusive os de justificativas e faltas (JUFA) e os de presença das mesárias e dos mesários.",
"29 de outubro, quinta-feira","Data-limite para digitação de códigos de ASE que reflitam na quitação eleitoral, exceto o ASE 167, e no registro de ausência de mesárias e mesários aos trabalhos eleitorais.",
NOVEMBRO DE 2026,,
"2 de novembro, segunda-feira","Data-limite para a conclusão do processamento dos arquivos de JUFA, incluídos os de presença das mesárias e dos mesários, bem como os arquivos gerados pela urna eletrônica e os de justificativas recebidas no segundo turno pelo e-Título.",
"2 de novembro, segunda-feira",Data-limite para atualização do cadastro com as biometrias de órgãos externos que foram validadas na urna.,
"3 de novembro, terça-feira",Reabertura do cadastro eleitoral e reinício da emissão da certidão de quitação eleitoral e da GRU pela internet e pelo Sistema ELO.,
"3 de novembro, terça-feira",Retomada do atendimento de eleitoras e eleitores nas unidades da Justiça Eleitoral.,
"3 de novembro, terça-feira","Reativação do serviço de autoatendimento eleitoral na internet para solicitação de alistamento, transferência e revisão.",
"8 de novembro, domingo",Lançamento automático do código de ASE 230 (motivo 1 ou 2) para candidatas e candidatos que não prestaram contas no prazo regulamentar no primeiro turno das Eleições 2026.,
"19 de novembro, quinta-feira",Lançamento automático do código de ASE 230 (motivo 1) para candidatas e candidatos que não prestaram contas no prazo regulamentar no segundo turno das Eleições 2026.,
DEZEMBRO DE 2026,,
"9 de dezembro, quarta-feira",Último dia para a digitação dos Requerimentos de Justificativa Eleitoral (RJE) recebidos pelo processo manual de recepção de justificativas no dia da eleição de primeiro e segundo turnos.,
"10 de dezembro, quinta-feira","Bloqueio de lançamento de ASE 167 para eleitoras e eleitores que não votaram no primeiro e no segundo turno, enviado por zona diversa.",
"19 de dezembro, sábado 
20 de dezembro, domingo","Manutenção preventiva da infraestrutura do cadastro eleitoral com indisponibilidade do Sistema ELO e de outros associados, em ambientes de produção e treinamento.",
JANEIRO DE 2027,,
"9 de janeiro, sábado","Inativação dos códigos de ASE 230 relativos às candidatas e aos candidatos que concorreram nas eleições de 2020 e que apresentaram contas extemporâneas, com comando do ASE 272.",
"14 de janeiro, quinta-feira",Geração de relação de eleitoras e eleitores aptos no primeiro e no segundo turnos para os quais haja registro de ASE 167 sem o lançamento do ASE 094 para o respectivo pleito.,
MARÇO DE 2027,,
"1º de março, segunda-feira",Data a partir da qual estarão disponíveis as relações contendo os nomes e os números de inscrição das eleitoras e dos eleitores identificadas(os) como faltosas (os) às três últimas eleições.,
"1º de março, segunda-feira","Início da contagem do prazo estabelecido pelo art. 131, § 2º, da Resolução nº 23.659/2021/TSE.",
"3 de março, quarta-feira",Data em que deverá ser afixado o edital com divulgação do início do procedimento de cancelamento de inscrições de eleitores faltosos a três pleitos consecutivos.,
ABRIL DE 2027,,
"30 de abril, sexta-feira",Último dia para a eleitora ou o eleitor comparecer ao cartório eleitoral para regularizar sua situação.,
MAIO DE 2027,,
"4 de maio, terça-feira",Cancelamento das inscrições das eleitoras e dos eleitores faltosos a três eleições consecutivas que não quitaram seus débitos.,
"5 de maio, quarta-feira",Data a partir da qual estarão disponíveis as relações contendo os nomes e os números de inscrição eleitoral cancelados por ausência aos três últimos pleitos.`;
